In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("train.csv")


In [6]:
def sex(s):
    if s.lower()=="male":
        return 0
    elif s.lower()=="female":
        return 1
df["sex_n"]=df["Sex"].apply(sex)


In [7]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  sex_n  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      1  
2      0  STON/O2. 3101282   7.9250   NaN        S      1  
3      0            113803  53.1000  C123        S      1  
4      0            373450   8.0500   NaN        S      0

In [8]:
x=df.drop("Survived",axis=1)
y=df["Survived"]

In [9]:


#df.dropna(inplace=True)

In [10]:
x.head()

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  sex_n  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S      0  
1  female  38.0      1      0          PC 17599  71.2833   C85        C      1  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S      1  
3  female  35.0      1      0            113803  53.1000  C123        S      1  
4    male  35.0      0      0            373450   8.0500   NaN        S      0

In [11]:
df.corr()

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443   
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225   
sex_n          -0.042939  0.543351 -0.131900 -0.093254  0.114631  0.245489   

                 Fare     sex_n  
PassengerId  0.012658 -0.042939  
Survived     0.257307  0.543351  
Pclass      -0.549500 -0.131900  
Age          0.096067 -0.093254  
SibSp        0.159651  0.114631  
Parch        0.216225  0.245489  
Fare         1.000000  0.182333  
sex_n        0.182333  1.000000

In [12]:
mat=df.corr()["Survived"]
selected_column=list(mat[(mat>0.1) | (mat<-0.1)].index)

In [13]:
selected_column.remove("Survived",)
#selected_column.remove("PassengerId")
selected_column

['Pclass', 'Fare', 'sex_n']

In [18]:
df["Fare"].fillna(df["Fare"].mean(),inplace=True)
df["Pclass"].fillna(df["Pclass"].mean(),inplace=True)
df["sex_n"].fillna(df["sex_n"].mean(),inplace=True)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test= train_test_split(x[selected_column],y,test_size=0.25,random_state=56)

In [29]:
x_tr_sc

array([[ 0.81420603, -0.41055255,  1.30554718],
       [ 0.81420603, -0.48966018, -0.76596236],
       [ 0.81420603, -0.50859414, -0.76596236],
       ...,
       [-0.38378875, -0.40692138,  1.30554718],
       [-1.58178353,  1.22044855, -0.76596236],
       [-1.58178353,  0.14812885,  1.30554718]])

In [22]:
scaler=StandardScaler()
scaler.fit(x_train)
x_tr_sc=scaler.transform(x_train)
x_ts_sc=scaler.transform(x_test)

# Support Vector Machine



In [80]:
from sklearn.svm import SVC

In [81]:
model1=SVC(kernel ="linear")
model1.fit(x_train,y_train)
model1.score(x_test,y_test)


0.8654708520179372

In [82]:
model1.predict([[2,  7,  0]])

array([0], dtype=int64)

In [83]:
model1.coef_

array([[-1.11706689e-03,  3.45846943e-05,  2.00025081e+00]])

# RandomForest

In [84]:
from sklearn.ensemble import RandomForestClassifier

In [85]:
model2=RandomForestClassifier(n_estimators=20)
model2.fit(x_tr_sc,y_train)
model2.score(x_ts_sc,y_test)

0.7713004484304933

In [86]:
model2.predict([[2,7,0]])

array([0], dtype=int64)

# DecisionTree

In [87]:
from sklearn.tree import DecisionTreeClassifier

In [88]:
model3=DecisionTreeClassifier()
model3.fit(x_train,y_train)
model3.score(x_test,y_test)

0.7757847533632287

In [89]:
model3.predict([[2,7,0]])

array([1], dtype=int64)

# K-Nearest Neighbours

In [90]:
from sklearn.neighbors import KNeighborsClassifier 

In [102]:
model4=KNeighborsClassifier(n_neighbors=2)
model4.fit(x_tr_sc,y_train)
model4.score(x_ts_sc,y_test)

0.8071748878923767

In [103]:
model4.predict([[2,7,0]])

array([1], dtype=int64)

# Logistic Regression

In [106]:
from sklearn.linear_model import LogisticRegression

In [110]:
model5=LogisticRegression(random_state = 0)
model5.fit(x_tr_sc,y_train)
model5.score(x_ts_sc,y_test)

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.8385650224215246

In [111]:
model5.predict([[2,7,0]])

array([0], dtype=int64)